name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: x64
          - os: macos-latest
            arch: universal

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: |
          if [[ "${{ matrix.arch }}" == "universal" ]]; then
            npm run make
          else
            npm run make -- --arch=${{ matrix.arch }}
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: out/make/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
