name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            targets: "@electron-forge/maker-deb"
            artifact_suffix: deb
          - os: ubuntu-latest
            arch: x64
            targets: "@electron-forge/maker-rpm"
            artifact_suffix: rpm
            install_rpm: true
          - os: macos-latest
            arch: arm64
            artifact_suffix: dmg
          - os: windows-latest
            arch: x64
            targets: "@electron-forge/maker-squirrel"
            artifact_suffix: squirrel
          - os: windows-latest
            arch: x64
            targets: "@rabbitholesyndrome/electron-forge-maker-portable"
            artifact_suffix: portable

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install RPM tools
        if: matrix.install_rpm
        run: sudo apt-get install -y rpm

      - name: Build app
        run: npm run make -- --arch=${{ matrix.arch }}${{ matrix.targets && format(' --targets {0}', matrix.targets) || '' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.artifact_suffix }}
          path: out/make/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
